### ISSUE TITLE
convert to an importable android module

### ISSUE THREAD

**Issue by Avinash-Bhat** [TristanWiley/FloatingActionMenu#1]
currently it's impossible to use this repo as a library. Any intention of making it into a module (and later a library, perhaps)?

**Comment by TristanWiley** [comment]
@Avinash-Bhat I will look into it, you really don't need to do anything except just put the class file in your app.

**Comment by Avinash-Bhat** [comment]
Yes, but for the bug fixes to this will not be available to the copied code.

If you want, I can give you a PR for this.

**Comment by TristanWiley** [comment]
Sure, that works :)

**Comment by Avinash-Bhat** [comment]
@TristanWiley done. check and let me know.

**Comment by TristanWiley** [comment]
I'm going to test it out and I'll most likely merge it when I do.
On Oct 21, 2015 10:31 PM, Avinash Ananth Narayan R notifications@github.com wrote:@TristanWiley done. check and let me know.

**Comment by TristanWiley** [comment]
Does it work for you? Perfectly?

**Comment by Avinash-Bhat** [comment]
The example code works perfectly.

**Comment by TristanWiley** [comment]
Thank you, I couldn't test it too much at school. Merged.
