### ISSUE TITLE
More Than 12 menu item

### ISSUE THREAD

**Issue by akash1223** [TristanWiley/FloatingActionMenu#11]
When 20 menu item added that time need to scroll these menu

**Comment by TristanWiley** [comment]
Wat

**Comment by akash1223** [comment]
When 20 menu item added that time need to scroll these menu

**Comment by akash1223** [comment]
When I added 20 FloatingActionButton inside FloatingActionMenu that time activity shows only 8  FloatingActionButton

**Comment by akash1223** [comment]
please help me

**Comment by akash1223** [comment]
I am also using https://android-arsenal.com/details/1/1684 but same problem here also

**Comment by TristanWiley** [comment]
I'd suggest not using 20 FABs... There's definitely a better way for you.

**Comment by akash1223** [comment]
I have list of employees so i want show all of then in list

**Comment by TristanWiley** [comment]
Yeah, I wouldn't do that.

Closed: Don't use 20 FABs in a FAM.

**Comment by akash1223** [comment]
it's bug in your code.....

**Comment by AdamMc331** [comment]
I don't think this is a good user experience at all. The floating action menu is only for a few quick items, Google recommends more than six. If you have a list of twenty items to choose from I recommend a RecyclerView.

**Comment by AdamMc331** [comment]
Recommends no more than six*
