### ISSUE TITLE
Can I put it on bintray.com?

### ISSUE THREAD

**Issue by callmepeanut** [TristanWiley/FloatingActionMenu#3]
I modified it to support both circle and line menu: https://github.com/callmepeanut/FloatingActionMenu
Can I put it on bintray.com?

**Comment by TristanWiley** [comment]
I'm going to be putting it on bintray tonight hopefully. I've been really busy, I'll get to it.

**Comment by callmepeanut** [comment]
ok

**Comment by ligi** [comment]
would also love to see it on bintray

**Comment by TristanWiley** [comment]
Will be putting it on tonight, if not then this weekend. Sorry, I've been super busy.

**Comment by ligi** [comment]
great! can you reopen the bug and close it once it is done to go from pull to push ;-)
