### ISSUE TITLE
Shadow gets cut off on FAB

### ISSUE THREAD

**Issue by TristanWiley** [TristanWiley/FloatingActionMenu#7]
When adding elevation and a shadow using the library the shadow gets cut off in a square.

Working on a fix, anyone else feel free to help.

**Comment by kevinah95** [comment]
I'm working on it.

**Comment by TristanWiley** [comment]
Awesome! 👍

**Comment by kevinah95** [comment]
I fix it!!! i'm really happy, this could be my first contribution for a project.
![screenshot_1476501003](https://cloud.githubusercontent.com/assets/7193395/19407034/d6c050aa-9252-11e6-9034-85a15840bf8d.png)

The steps were:
1. Add a local.properties file, beacuse the gradle asked me for it.
2. Googling some, I find this: http://stackoverflow.com/a/35324991 and that's the solution. 

I'll make a pull request. I'm a noob on it 😄.

**Comment by TristanWiley** [comment]
Awesome! I'll have to look later, it's late here, might not be until tomorrow when I can check.

**Comment by kevinah95** [comment]
Cool, I hope I have done the pull request well  😀

**Comment by TristanWiley** [comment]
Closed in #10
